/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/ai/': RouteRecordInfo<
      '/ai/',
      '/ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/allocations/': RouteRecordInfo<
      '/allocations/',
      '/allocations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendar/': RouteRecordInfo<
      '/calendar/',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendar-grid/': RouteRecordInfo<
      '/calendar-grid/',
      '/calendar-grid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/': RouteRecordInfo<
      '/catalog/',
      '/catalog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gantt/': RouteRecordInfo<
      '/gantt/',
      '/gantt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/kanban/': RouteRecordInfo<
      '/kanban/',
      '/kanban',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/': RouteRecordInfo<
      '/reports/',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resources/': RouteRecordInfo<
      '/resources/',
      '/resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/teams/': RouteRecordInfo<
      '/teams/',
      '/teams',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/ai/index.vue': {
      routes:
        | '/ai/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/allocations/index.vue': {
      routes:
        | '/allocations/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/calendar/index.vue': {
      routes:
        | '/calendar/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/calendar-grid/index.vue': {
      routes:
        | '/calendar-grid/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/index.vue': {
      routes:
        | '/catalog/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/gantt/index.vue': {
      routes:
        | '/gantt/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/kanban/index.vue': {
      routes:
        | '/kanban/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reports/index.vue': {
      routes:
        | '/reports/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/resources/index.vue': {
      routes:
        | '/resources/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/teams/index.vue': {
      routes:
        | '/teams/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
