pub mod allocations;
pub mod projects;
pub mod resources;
pub mod skills;
pub mod tags;
pub mod tasks;
pub use allocations::AllocationsRepo;
pub use projects::ProjectsRepo;
pub use resources::ResourcesRepo;
pub use skills::SkillsRepo;
pub use tags::TagsRepo;
pub use tasks::{TaskCreate, TaskDepsRepo, TasksRepo};